name: CI

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Step 1- Checkout main branch from Github
        uses: actions/checkout@v2

      - name: Step 2- Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # You can change this to another distribution if needed
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ secrets.GITHUB_ACTOR }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Step 3- Build Maven Project
        run: mvn -B package --file pom.xml

      - name: Step 4- List the current directory
        run: ls -a

      - name: Step 5- What is in the target folder
        run: |
          cd target
          ls -a
